import spotipy


class Playlist:
    def __init__(self, spotify: spotipy.Spotify, name: str) -> None:
        self.spotify = spotify
        self.name = name
        self.id = None
        self._create()

    def _create(self):
        user = self.spotify.current_user()
        description = "Playlist generated by Spotify Optimiser"
        created = self.spotify.user_playlist_create(user['id'], self.name, public=False, description=description)
        self.id = created['id']

    def add(self, track_id):
        self.spotify.playlist_add_items(self.id, [track_id])
